spring:
  application:
    name: lionproject2-backend

  profiles:
    active: local

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

redisson:
  address: ${REDISSON_ADDRESS:redis://${spring.data.redis.host}:${spring.data.redis.port}}
  username: ${REDISSON_USERNAME:}
  password: ${REDISSON_PASSWORD:${spring.data.redis.password:}}
  database: ${REDISSON_DATABASE:0}
  timeout: ${REDISSON_TIMEOUT_MS:3000}
  connect-timeout: ${REDISSON_CONNECT_TIMEOUT_MS:10000}
  idle-connection-timeout: ${REDISSON_IDLE_CONNECTION_TIMEOUT_MS:10000}
  retry-attempts: ${REDISSON_RETRY_ATTEMPTS:3}
  retry-interval: ${REDISSON_RETRY_INTERVAL_MS:1500}
  connection-pool-size: ${REDISSON_CONNECTION_POOL_SIZE:24}
  connection-minimum-idle-size: ${REDISSON_CONNECTION_MIN_IDLE_SIZE:8}
  threads: ${REDISSON_THREADS:16}
  netty-threads: ${REDISSON_NETTY_THREADS:32}

portone:
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  api-secret: ${PORTONE_API_SECRET}

payment:
  inicis:
    mid: ${INICIS_MID:INIpaytest}
    signkey: ${INICIS_SIGNKEY:SU5JTElURV9URVNUX1NJR05LRVk=}
    ini-api-key: ${INICIS_API_KEY:test}
    ini-api-iv: ${INICIS_API_IV:HYb3yQ4f65QL89==}
